const puzzles = [
  { category:'OCEAN ESCAPE', title:'Blue Horizon', words:['OCEAN','WHALE','CORAL','TIDE','SHELL','WAVE'], rows:['OCEANQPLMK','WHALEZRTYU','CORALXVNBD','TIDEKJHGFD','SHELLQWERT','WAVEZXCVMN','APLKJHGFDS','QWERTYUIOP','MNBVCXZLKJ','POIUYTREWA'], colors:['#75d7bd','#9ed6ef','#ffd166','#f4a58c','#b9a8ed','#75d7bd'] },
  { category:'TRAVEL TRAIL', title:'Postcard Path', words:['TICKET','HOTEL','TRAIN','MAP','CAMERA','BEACH'], rows:['TICKETQWZX','HOTELMNBCV','TRAINASDFG','MAPQWERTYU','CAMERAZXCV','BEACHPLMKO','QAZWSXEDCR','FVTGBYHNUJ','MIKOLPZXCV','BNMASDFGHJ'], colors:['#9ed6ef','#ffd166','#f4a58c','#b9a8ed','#75d7bd','#9ed6ef'] },
  { category:'TASTY WORDS', title:'Fresh & Fun', words:['APPLE','BERRY','BREAD','MANGO','HONEY','LEMON'], rows:['APPLEQWERT','BERRYZXCVB','BREADASDFG','MANGOQWERT','HONEYZXCVB','LEMONASDFG','QWERTYUIOP','ZXCVBNMLKJ','ASDFGHJKLQ','POIUYTREWA'], colors:['#f4a58c','#b9a8ed','#ffd166','#75d7bd','#f4a58c','#9ed6ef'] }
];
let puzzleIndex = 0, found = [], hints = 3, seconds = 84, selected = [], timerId, soundOn = true;
const q = new URLSearchParams(location.search); const forcedScreen = q.get('screen');
const $ = (id) => document.getElementById(id);
function activePuzzle(){ return puzzles[puzzleIndex]; }
function isPartOfWord(row,col){ return activePuzzle().words.find(word => activePuzzle().rows[row].slice(0,word.length) === word && col < word.length); }
function renderBoard(){ const board=$('letterBoard'); board.innerHTML=''; activePuzzle().rows.join('').split('').forEach((letter,index)=>{ const cell=document.createElement('button'); cell.className='cell'; cell.textContent=letter; cell.dataset.row=Math.floor(index/10); cell.dataset.col=index%10; cell.setAttribute('aria-label',`Row ${Math.floor(index/10)+1}, letter ${letter}`); const word=isPartOfWord(Math.floor(index/10),index%10); if(word && found.includes(word)) cell.classList.add('found'); board.append(cell); }); renderWords(); }
function renderWords(){ const words=activePuzzle().words; $('wordList').innerHTML=words.map((word,i)=>`<div class="word-chip ${found.includes(word)?'done':''}" style="--word:${activePuzzle().colors[i]}">${word}</div>`).join(''); $('progressText').textContent=`${found.length} / ${words.length}`; $('foundCount').textContent=`${found.length} FOUND`; }
function updateHeader(){ const p=activePuzzle(); $('categoryLabel').textContent=p.category; $('levelTitle').textContent=p.title; $('hintCount').textContent=hints; $('timerText').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0'); }
function setupPuzzle(index=0){ puzzleIndex=index; found=[]; hints=3; seconds=84; updateHeader(); renderBoard(); clearInterval(timerId); timerId=setInterval(()=>{seconds=Math.max(0,seconds-1);updateHeader();},1000); }
function showLine(cells){ const line=$('selectionLine'); if(cells.length<2){line.style.display='none';return;} const wrap=$('boardWrap').getBoundingClientRect(), a=cells[0].getBoundingClientRect(), b=cells[cells.length-1].getBoundingClientRect(); const x1=a.left+a.width/2-wrap.left, y1=a.top+a.height/2-wrap.top, x2=b.left+b.width/2-wrap.left, y2=b.top+b.height/2-wrap.top, d=Math.hypot(x2-x1,y2-y1); line.style.display='block'; line.style.width=d+'px'; line.style.left=x1+'px'; line.style.top=(y1-14)+'px'; line.style.transform=`rotate(${Math.atan2(y2-y1,x2-x1)}rad)`; }
function clearSelection(){ selected.forEach(c=>c.classList.remove('preview')); selected=[]; $('selectionLine').style.display='none'; }
function finishSelection(){ if(!selected.length)return; const text=selected.map(c=>c.textContent).join(''); const reversed=[...text].reverse().join(''); const target=activePuzzle().words.find(w=>w===text||w===reversed); if(target && !found.includes(target)){ found.push(target); selected.forEach(c=>c.classList.add('found')); renderWords(); if(found.length===activePuzzle().words.length){ clearInterval(timerId); $('winTime').textContent=$('timerText').textContent; $('winMessage').textContent=`All ${found.length} words found — your streak is glowing!`; setTimeout(()=>{$('winOverlay').classList.add('show');$('winOverlay').setAttribute('aria-hidden','false');},260); } } clearSelection(); }
function cellsBetween(start,end){ const r1=+start.dataset.row,c1=+start.dataset.col,r2=+end.dataset.row,c2=+end.dataset.col,dr=r2-r1,dc=c2-c1, steps=Math.max(Math.abs(dr),Math.abs(dc)); if(!steps || (dr && dc && Math.abs(dr)!==Math.abs(dc))) return [start]; const sr=dr===0?0:dr/Math.abs(dr), sc=dc===0?0:dc/Math.abs(dc), list=[]; for(let i=0;i<=steps;i++){const c=document.querySelector(`.cell[data-row="${r1+i*sr}"][data-col="${c1+i*sc}"]`);if(c)list.push(c)} return list; }
function cellFromPoint(e){ const p=e.touches?e.touches[0]:e; return document.elementFromPoint(p.clientX,p.clientY)?.closest('.cell'); }
function selectTo(cell){ if(!selected.length||!cell)return; selected.forEach(c=>c.classList.remove('preview')); selected=cellsBetween(selected[0],cell); selected.forEach(c=>c.classList.add('preview')); showLine(selected); }
function useHint(){ const word=activePuzzle().words.find(w=>!found.includes(w)); if(!word||!hints)return; hints--; updateHeader(); const nodes=[...document.querySelectorAll('.cell')].filter(n=>+n.dataset.row===activePuzzle().rows.findIndex(row=>row.startsWith(word))&&+n.dataset.col<word.length); nodes.forEach(n=>n.classList.add('hinted')); setTimeout(()=>nodes.forEach(n=>n.classList.remove('hinted')),1900); }
function renderLevels(){ $('levelCards').innerHTML=puzzles.map((p,i)=>`<button class="level-card" data-level="${i}"><span class="level-number">${String(i+1).padStart(2,'0')}</span><span><b>${p.title}</b><small>${p.category} · ${p.words.length} words</small></span><i>›</i></button>`).join(''); }
function activateScreenMode(){ if(forcedScreen==='welcome') return; $('welcomeOverlay').classList.add('hidden'); if(forcedScreen==='levels') $('levelsPanel').classList.add('open'); if(forcedScreen==='win'){ found=[...activePuzzle().words];renderBoard();$('winTime').textContent='00:42';$('winOverlay').classList.add('show'); } if(forcedScreen==='hint'){ setTimeout(useHint,300); } }
document.addEventListener('DOMContentLoaded',()=>{ setupPuzzle(); renderLevels(); activateScreenMode(); $('startButton').onclick=()=>{$('welcomeOverlay').classList.add('hidden')}; $('levelsButton').onclick=()=>$('levelsPanel').classList.add('open'); $('closeLevels').onclick=()=>$('levelsPanel').classList.remove('open'); $('newGameButton').onclick=()=>setupPuzzle(puzzleIndex); $('hintButton').onclick=useHint; $('soundButton').onclick=()=>{soundOn=!soundOn;$('soundButton').textContent=soundOn?'♬':'×'}; $('nextButton').onclick=()=>{$('winOverlay').classList.remove('show');setupPuzzle((puzzleIndex+1)%puzzles.length)}; $('replayButton').onclick=()=>{$('winOverlay').classList.remove('show');setupPuzzle(puzzleIndex)}; $('levelCards').onclick=(e)=>{const btn=e.target.closest('[data-level]');if(btn){$('levelsPanel').classList.remove('open');setupPuzzle(+btn.dataset.level)}}; const board=$('boardWrap'); board.addEventListener('pointerdown',e=>{const cell=cellFromPoint(e);if(cell){board.setPointerCapture?.(e.pointerId);clearSelection();selected=[cell];cell.classList.add('preview');}}); board.addEventListener('pointermove',e=>selectTo(cellFromPoint(e))); board.addEventListener('pointerup',finishSelection); board.addEventListener('pointercancel',clearSelection); });
